name=input('What is your name:')
age=int(input('What is your age:'))
income=float(input('What is your income:'))
print('Here is the data you entered:')
print(f'Name:{name}, Age:{age}, Income:{income}')
